import path from 'node:path'

import unimportPlugin from 'unimport/unplugin'
import autoImport from 'unplugin-auto-import/vite'

import {
  getConfig,
  getPaths,
  importStatementPath,
} from '@cedarjs/project-config'

export function cedarAutoImportsPlugin() {
  // Need the project config to know if trusted graphql documents is being used
  // and decide to use the gql tag import or the trusted document gql function
  // generated by code gen client preset
  const config = getConfig()
  const cedarPaths = getPaths()
  const useTrustedDocumentsGqlTag = config?.graphql?.trustedDocuments

  return [
    autoImport({
      // targets to transform
      include: [
        /web\/.*\.[tj]sx?$/,
        // Assume we want the trusted documents gql tag import in all .jsx and
        // .tsx files
        /\.[tj]sx$/,
      ],

      // global imports to register
      imports: [
        // import gql from 'graphql-tag'
        !useTrustedDocumentsGqlTag && {
          'graphql-tag': ['gql'],
        },
        // import { gql } from 'src/graphql/gql'
        useTrustedDocumentsGqlTag && {
          [importStatementPath(
            path.join(cedarPaths.web.base, 'src', 'graphql', 'gql'),
          )]: ['gql'],
        },
      ].filter(<T>(v?: T | false): v is T => Boolean(v)),

      // Types aren't important since the output is ephemeral
      dts: false,
    }),
    autoImport({
      // targets to transform
      include: [/\.[tj]sx?$/],

      // global imports to register
      imports: [
        {
          '@cedarjs/context': ['context'],
        },
      ],

      // Types aren't important since the output is ephemeral
      dts: false,
    }),
    autoImport({
      // targets to transform
      include: [/api\/.*\.[tj]sx?$/],

      // global imports to register
      imports: [
        // import gql from 'graphql-tag'
        {
          'graphql-tag': ['gql'],
        },
      ],

      // Types aren't important since the output is ephemeral
      dts: false,
    }),
    unimportPlugin.vite({
      imports: [
        // import React from 'react'
        {
          name: 'default',
          as: 'React',
          from: 'react',
        },
      ],
    }),
  ]
}
